### PR TITLE
Refresh plugin

### PR DESCRIPTION
**Pull request by basil**
CC @dwnusbaum @oleg-nenashev @mramonleon

### CODE REVIEW

**Comment by basil** [comment]
/reviewer apache-httpcomponents-client-4-api-plugin-developers

**Comment by basil** [comment]
/reviewer jenkinsci/apache-httpcomponents-client-4-api-plugin-developers

**Review by oleg-nenashev — APPROVED** [review]
LGTM.

**Comment by oleg-nenashev** [comment]
Do you need a release right away?

**Comment by basil** [comment]
A release would be appreciated for BOM/PCT purposes, as it would allow me to remove a workaround in `jenkinsci/bom` that only exists due to the outdated plugin parent POM.

**Comment by basil** [comment]
/reviewer @jenkinsci/apache-httpcomponents-client-4-api-plugin-developers

**Comment by timja** [comment]
@dwnusbaum / @oleg-nenashev would it be possible for someone to release this so we can remove a hack in bom please?

**Comment by basil** [comment]
Thank you!

**Comment by dwnusbaum** [comment]
@basil See https://github.com/jenkinsci/apache-httpcomponents-client-4-api-plugin/tree/apache-httpcomponents-client-4-api-4.5.13-138.v4e7d9a_7b_a_e61. CD is not working for this repository because it's name is too long, see https://github.com/jenkins-infra/repository-permissions-updater/issues/2681, so this was a manual release and I will update release notes shortly.

**Comment by basil** [comment]
Oh wow, thanks again!

**Pull request merged**
