### PR TITLE
Enable CD

### PR DESCRIPTION
**Pull request by dwnusbaum**
See https://github.com/jenkins-infra/repository-permissions-updater/pull/2680.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by jtnord — APPROVED** [review]
I'm not a great fan of the reusable workflow changing without any PR where it is used, but I hope this changes so infrequently that we just do not care so much.

**Comment by dwnusbaum** [comment]
Hmm, I did not read the docs carefully enough:

> Once that has been merged, start checking https://github.com/jenkinsci/your-plugin/settings/secrets/actions until you see MAVEN_TOKEN and MAVEN_USERNAME appear under Repository secrets.

I don't see these yet, and the release failed:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project apache-httpcomponents-client-4-api: Failed to deploy artifacts: Could not transfer artifact org.jenkins-ci.plugins:apache-httpcomponents-client-4-api:hpi:4.5.13-138.v4e7d9a_7b_a_e61 from/to maven.jenkins-ci.org (https://repo.jenkins-ci.org/releases/): authentication failed for https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/apache-httpcomponents-client-4-api/4.5.13-138.v4e7d9a_7b_a_e61/apache-httpcomponents-client-4-api-4.5.13-138.v4e7d9a_7b_a_e61.hpi, status: 401 Unauthorized -> [Help 1]
```

I'll check back later to see if the secrets get created.

**Comment by dwnusbaum** [comment]
CD releases do not work currently because this repository's name is too long, see https://github.com/jenkins-infra/repository-permissions-updater/issues/2681.

**Comment by jetersen** [comment]
@dwnusbaum should be fixed by https://github.com/jenkins-infra/repository-permissions-updater/pull/2716

**Comment by jetersen** [comment]
@dwnusbaum confirmed by daniel: https://github.com/jenkins-infra/repository-permissions-updater/issues/2681#issuecomment-1212988047

**Pull request merged**
